---
# tasks file for system_hardening
- name: Upgrade operating system
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: Update and upgrade system packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
  become: true

- name: Ensure that UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
  become: true

- name: Make a UFW exception for SSH
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  become: true

- name: Allow new incoming SYN packets on TCP port 3333 for SSH
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3333
    ctstate: NEW
    jump: ACCEPT
    comment: Accept new SSH connections.
  become: true

- name: Ensure that iptables-persistent is installed
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
  become: true

- name: Ensure that the netfilter-persistent service is started
  ansible.builtin.service:
    name: netfilter-persistent.service
    state: started
  become: true

- name: Save current iptables
  ansible.builtin.shell: netfilter-persistent save
  become: true

- name: Change SSH port in SSHD configuration file
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port 3333"
  become: true

- name: Disable password login in SSHD configuration file
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  become: true

- name: Restart SSH service
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
